######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 30 23:30:30 2023
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gas.h
FORMS += QtGas.ui
SOURCES += gas.cpp main.cpp
